type=item
matchItems=minecraft:shield
nbt.display.Name=pattern:*Dreieckschild
nbt.display.Lore.*=pattern:*Hilligsaiwiz*
weight=2
model=./hilligsaiwiz.json
model.shield_blocking=./hilligsaiwiz_blocking.json



