type=item
matchItems=minecraft:shield
nbt.display.Name=pattern:*Dreieckschild
nbt.display.Lore.*=pattern:*Kreuzwacht*
weight=2
model=./kreuzwacht.json
model.shield_blocking=./kreuzwacht_blocking.json



