type=item
matchItems=minecraft:shield
nbt.display.Name=pattern:*Dreieckschild
nbt.display.Lore.*=pattern:*Lindenholde*
weight=2
model=./lindenholde.json
model.shield_blocking=./lindenholde_blocking.json