type=item
matchItems=minecraft:shield
nbt.display.Name=pattern:*Dreieckschild
nbt.display.Lore.*=pattern:*Seeschlange*
weight=2
model=./seeschlange.json
model.shield_blocking=./seeschlange_blocking.json