type=item
matchItems=minecraft:shield
nbt.display.Name=pattern:*Dreieckschild
nbt.display.Lore.*=pattern:*Sturmkliff*
weight=2
model=./sturmkliff.json
model.shield_blocking=./sturmkliff_blocking.json



