type=item
matchItems=minecraft:shield
nbt.display.Name=pattern:*Dreieckschild
nbt.display.Lore.*=pattern:*Wei*wasserhaven*
weight=2
model=./weisswasserhaven.json
model.shield_blocking=./weisswasserhaven_blocking.json